/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: main
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize};

/// struct for passing parameters to the method [`add_service`]
#[derive(Clone, Debug, Default)]
pub struct AddServiceParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub add_service_request: models::AddServiceRequest,
}

/// struct for passing parameters to the method [`add_target`]
#[derive(Clone, Debug, Default)]
pub struct AddTargetParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub load_balancer_add_target: models::LoadBalancerAddTarget,
}

/// struct for passing parameters to the method [`attach_load_balancer_to_network`]
#[derive(Clone, Debug, Default)]
pub struct AttachLoadBalancerToNetworkParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub attach_load_balancer_to_network_request: models::AttachLoadBalancerToNetworkRequest,
}

/// struct for passing parameters to the method [`change_algorithm`]
#[derive(Clone, Debug, Default)]
pub struct ChangeAlgorithmParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub load_balancer_algorithm: models::LoadBalancerAlgorithm,
}

/// struct for passing parameters to the method [`change_load_balancer_protection`]
#[derive(Clone, Debug, Default)]
pub struct ChangeLoadBalancerProtectionParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub change_load_balancer_protection_request: models::ChangeLoadBalancerProtectionRequest,
}

/// struct for passing parameters to the method [`change_reverse_dns_entry_for_this_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct ChangeReverseDnsEntryForThisLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    /// Select the IP address for which to change the DNS entry by passing `ip`. It can be either IPv4 or IPv6. The target hostname is set by passing `dns_ptr`, which must be a fully qualified domain name (FQDN) without trailing dot.
    pub dns_ptr_change: models::DnsPtrChange,
}

/// struct for passing parameters to the method [`change_type_of_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct ChangeTypeOfLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub change_type_of_load_balancer_request: models::ChangeTypeOfLoadBalancerRequest,
}

/// struct for passing parameters to the method [`create_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct CreateLoadBalancerParams {
    pub create_load_balancer_request: models::CreateLoadBalancerRequest,
}

/// struct for passing parameters to the method [`delete_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct DeleteLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
}

/// struct for passing parameters to the method [`delete_service`]
#[derive(Clone, Debug, Default)]
pub struct DeleteServiceParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub delete_service_request: models::DeleteServiceRequest,
}

/// struct for passing parameters to the method [`detach_load_balancer_from_network`]
#[derive(Clone, Debug, Default)]
pub struct DetachLoadBalancerFromNetworkParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub detach_load_balancer_from_network_request: models::DetachLoadBalancerFromNetworkRequest,
}

/// struct for passing parameters to the method [`disable_public_interface_of_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct DisablePublicInterfaceOfLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
}

/// struct for passing parameters to the method [`enable_public_interface_of_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct EnablePublicInterfaceOfLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
}

/// struct for passing parameters to the method [`get_action_for_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct GetActionForLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    /// ID of the Action.
    pub action_id: i64,
}

/// struct for passing parameters to the method [`get_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct GetLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
}

/// struct for passing parameters to the method [`get_load_balancer_action`]
#[derive(Clone, Debug, Default)]
pub struct GetLoadBalancerActionParams {
    /// ID of the Action.
    pub id: i64,
}

/// struct for passing parameters to the method [`get_metrics_for_loadbalancer`]
#[derive(Clone, Debug, Default)]
pub struct GetMetricsForLoadbalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    /// Type of metrics to get.
    pub r#type: Vec<String>,
    /// Start of period to get Metrics for (must be in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
    pub start: String,
    /// End of period to get Metrics for (must be in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) format).
    pub end: String,
    /// Resolution of results in seconds.
    pub step: Option<String>,
}

/// struct for passing parameters to the method [`list_actions_for_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct ListActionsForLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    /// Sort actions by field and direction. May be used multiple times.  For more information, see \"Sorting\".
    pub sort: Option<Vec<String>>,
    /// Filter the actions by status. May be used multiple times.  The response will only contain actions matching the specified statuses.
    pub status: Option<Vec<String>>,
    /// Page number to return. For more information, see \"Pagination\".
    pub page: Option<i64>,
    /// Maximum number of entries returned per page. For more information, see \"Pagination\".
    pub per_page: Option<i64>,
}

/// struct for passing parameters to the method [`list_load_balancer_actions`]
#[derive(Clone, Debug, Default)]
pub struct ListLoadBalancerActionsParams {
    /// Filter the actions by ID. May be used multiple times.  The response will only contain actions matching the specified IDs.
    pub id: Option<Vec<i64>>,
    /// Sort actions by field and direction. May be used multiple times.  For more information, see \"Sorting\".
    pub sort: Option<Vec<String>>,
    /// Filter the actions by status. May be used multiple times.  The response will only contain actions matching the specified statuses.
    pub status: Option<Vec<String>>,
    /// Page number to return. For more information, see \"Pagination\".
    pub page: Option<i64>,
    /// Maximum number of entries returned per page. For more information, see \"Pagination\".
    pub per_page: Option<i64>,
}

/// struct for passing parameters to the method [`list_load_balancers`]
#[derive(Clone, Debug, Default)]
pub struct ListLoadBalancersParams {
    /// Sort resources by field and direction. May be used multiple times.  For more information, see \"Sorting\".
    pub sort: Option<Vec<String>>,
    /// Filter resources by their name.  The response will only contain the resources matching exactly the specified name.
    pub name: Option<String>,
    /// Filter resources by labels.  The response will only contain resources matching the label selector. For more information, see \"Label Selector\".
    pub label_selector: Option<String>,
    /// Page number to return. For more information, see \"Pagination\".
    pub page: Option<i64>,
    /// Maximum number of entries returned per page. For more information, see \"Pagination\".
    pub per_page: Option<i64>,
}

/// struct for passing parameters to the method [`remove_target`]
#[derive(Clone, Debug, Default)]
pub struct RemoveTargetParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub remove_target_request: models::RemoveTargetRequest,
}

/// struct for passing parameters to the method [`replace_load_balancer`]
#[derive(Clone, Debug, Default)]
pub struct ReplaceLoadBalancerParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub replace_load_balancer_request: models::ReplaceLoadBalancerRequest,
}

/// struct for passing parameters to the method [`update_service`]
#[derive(Clone, Debug, Default)]
pub struct UpdateServiceParams {
    /// ID of the Load Balancer.
    pub id: i64,
    pub update_load_balancer_service: models::UpdateLoadBalancerService,
}

/// struct for typed errors of method [`add_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddServiceError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`add_target`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddTargetError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attach_load_balancer_to_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttachLoadBalancerToNetworkError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_algorithm`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeAlgorithmError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_load_balancer_protection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeLoadBalancerProtectionError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_reverse_dns_entry_for_this_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeReverseDnsEntryForThisLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`change_type_of_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangeTypeOfLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteServiceError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`detach_load_balancer_from_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DetachLoadBalancerFromNetworkError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_public_interface_of_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisablePublicInterfaceOfLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enable_public_interface_of_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnablePublicInterfaceOfLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_action_for_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetActionForLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_load_balancer_action`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLoadBalancerActionError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_metrics_for_loadbalancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMetricsForLoadbalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_actions_for_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListActionsForLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_load_balancer_actions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListLoadBalancerActionsError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_load_balancers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListLoadBalancersError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_target`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveTargetError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`replace_load_balancer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplaceLoadBalancerError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_service`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateServiceError {
    Status4xx(models::ErrorResponse),
    Status5xx(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// Adds a service to a Load Balancer.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `412` | `source_port_already_used` | The source port you are trying to add is already in use |
pub async fn add_service(
    configuration: &configuration::Configuration,
    params: AddServiceParams,
) -> Result<models::AddServiceResponse, Error<AddServiceError>> {
    add_service_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`add_service`], but also returns the response headers.
pub async fn add_service_with_headers(
    configuration: &configuration::Configuration,
    params: AddServiceParams,
) -> Result<(models::AddServiceResponse, reqwest::header::HeaderMap), Error<AddServiceError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let add_service_request = params.add_service_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/add_service",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&add_service_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<AddServiceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Adds a target to a Load Balancer.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `422` | `ip_not_in_vswitch_subnet` | The IP you are trying to add does not belong to the vswitch subnet of the attached network | | `422` | `ip_not_owned` | The IP you are trying to add as a target is not owned by the Project owner | | `422` | `ip_not_assigned_to_server` | The specified IP is neither the Primary IPv4 address nor in the IPv6 subnet of the given Server | | `422` | `load_balancer_public_interface_disabled` | The Load Balancer's public network interface is disabled | | `422` | `load_balancer_not_attached_to_network` | The Load Balancer is not attached to a network | | `422` | `network_has_no_vswitch_subnet` | The given IP is private but attached network does not have a vswitch subnet | | `422` | `resolve_cloud_private_targets_error` | The server you are trying to add as a target is not attached to the same network as the Load Balancer | | `422` | `resolve_cloud_public_targets_error` | The server that you are trying to add as a public target does not have a public IPv4 address | | `422` | `target_already_defined` | The Load Balancer target you are trying to define is already defined |
pub async fn add_target(
    configuration: &configuration::Configuration,
    params: AddTargetParams,
) -> Result<models::AddTargetResponse, Error<AddTargetError>> {
    add_target_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`add_target`], but also returns the response headers.
pub async fn add_target_with_headers(
    configuration: &configuration::Configuration,
    params: AddTargetParams,
) -> Result<(models::AddTargetResponse, reqwest::header::HeaderMap), Error<AddTargetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let load_balancer_add_target = params.load_balancer_add_target;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/add_target",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&load_balancer_add_target);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<AddTargetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Attach a Load Balancer to a Network.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `422` | `load_balancer_already_attached` | The Load Balancer is already attached to a network | | `422` | `ip_not_available` | The provided Network IP is not available | | `422` | `no_subnet_available` | No Subnet or IP is available for the Load Balancer within the network |
pub async fn attach_load_balancer_to_network(
    configuration: &configuration::Configuration,
    params: AttachLoadBalancerToNetworkParams,
) -> Result<models::AttachLoadBalancerToNetworkResponse, Error<AttachLoadBalancerToNetworkError>> {
    attach_load_balancer_to_network_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`attach_load_balancer_to_network`], but also returns the response headers.
pub async fn attach_load_balancer_to_network_with_headers(
    configuration: &configuration::Configuration,
    params: AttachLoadBalancerToNetworkParams,
) -> Result<
    (
        models::AttachLoadBalancerToNetworkResponse,
        reqwest::header::HeaderMap,
    ),
    Error<AttachLoadBalancerToNetworkError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let attach_load_balancer_to_network_request = params.attach_load_balancer_to_network_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/attach_to_network",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&attach_load_balancer_to_network_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<AttachLoadBalancerToNetworkError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Change the algorithm that determines to which target new requests are sent.
pub async fn change_algorithm(
    configuration: &configuration::Configuration,
    params: ChangeAlgorithmParams,
) -> Result<models::ChangeAlgorithmResponse, Error<ChangeAlgorithmError>> {
    change_algorithm_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`change_algorithm`], but also returns the response headers.
pub async fn change_algorithm_with_headers(
    configuration: &configuration::Configuration,
    params: ChangeAlgorithmParams,
) -> Result<
    (models::ChangeAlgorithmResponse, reqwest::header::HeaderMap),
    Error<ChangeAlgorithmError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let load_balancer_algorithm = params.load_balancer_algorithm;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/change_algorithm",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&load_balancer_algorithm);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ChangeAlgorithmError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Changes the protection configuration of a Load Balancer.
pub async fn change_load_balancer_protection(
    configuration: &configuration::Configuration,
    params: ChangeLoadBalancerProtectionParams,
) -> Result<models::ChangeLoadBalancerProtectionResponse, Error<ChangeLoadBalancerProtectionError>>
{
    change_load_balancer_protection_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`change_load_balancer_protection`], but also returns the response headers.
pub async fn change_load_balancer_protection_with_headers(
    configuration: &configuration::Configuration,
    params: ChangeLoadBalancerProtectionParams,
) -> Result<
    (
        models::ChangeLoadBalancerProtectionResponse,
        reqwest::header::HeaderMap,
    ),
    Error<ChangeLoadBalancerProtectionError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let change_load_balancer_protection_request = params.change_load_balancer_protection_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/change_protection",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&change_load_balancer_protection_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ChangeLoadBalancerProtectionError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Changes the hostname that will appear when getting the hostname belonging to the public IPs (IPv4 and IPv6) of this Load Balancer.  Floating IPs assigned to the Server are not affected by this.
pub async fn change_reverse_dns_entry_for_this_load_balancer(
    configuration: &configuration::Configuration,
    params: ChangeReverseDnsEntryForThisLoadBalancerParams,
) -> Result<
    models::ChangeReverseDnsEntryForThisLoadBalancerResponse,
    Error<ChangeReverseDnsEntryForThisLoadBalancerError>,
> {
    change_reverse_dns_entry_for_this_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`change_reverse_dns_entry_for_this_load_balancer`], but also returns the response headers.
pub async fn change_reverse_dns_entry_for_this_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: ChangeReverseDnsEntryForThisLoadBalancerParams,
) -> Result<
    (
        models::ChangeReverseDnsEntryForThisLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<ChangeReverseDnsEntryForThisLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let dns_ptr_change = params.dns_ptr_change;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/change_dns_ptr",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&dns_ptr_change);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ChangeReverseDnsEntryForThisLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Changes the type (Max Services, Max Targets and Max Connections) of a Load Balancer.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `422` | `invalid_load_balancer_type` | The Load Balancer type does not fit for the given Load Balancer |
pub async fn change_type_of_load_balancer(
    configuration: &configuration::Configuration,
    params: ChangeTypeOfLoadBalancerParams,
) -> Result<models::ChangeTypeOfLoadBalancerResponse, Error<ChangeTypeOfLoadBalancerError>> {
    change_type_of_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`change_type_of_load_balancer`], but also returns the response headers.
pub async fn change_type_of_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: ChangeTypeOfLoadBalancerParams,
) -> Result<
    (
        models::ChangeTypeOfLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<ChangeTypeOfLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let change_type_of_load_balancer_request = params.change_type_of_load_balancer_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/change_type",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&change_type_of_load_balancer_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ChangeTypeOfLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Creates a Load Balancer.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `412` | `source_port_already_used` | The source port you are trying to add is already in use | | `422` | `ip_not_owned` | The IP is not owned by the owner of the project of the Load Balancer | | `422` | `load_balancer_not_attached_to_network` | The Load Balancer is not attached to a network | | `422` | `resolve_cloud_private_targets_error` | The server you are trying to add as a target is not attached to the same network as the Load Balancer | | `422` | `resolve_cloud_public_targets_error` | The server that you are trying to add as a public target does not have a public IPv4 address | | `422` | `target_already_defined` | The Load Balancer target you are trying to define is already defined |
pub async fn create_load_balancer(
    configuration: &configuration::Configuration,
    params: CreateLoadBalancerParams,
) -> Result<models::CreateLoadBalancerResponse, Error<CreateLoadBalancerError>> {
    create_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`create_load_balancer`], but also returns the response headers.
pub async fn create_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: CreateLoadBalancerParams,
) -> Result<
    (
        models::CreateLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<CreateLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let create_load_balancer_request = params.create_load_balancer_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers", local_base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&create_load_balancer_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<CreateLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Deletes a Load Balancer.
pub async fn delete_load_balancer(
    configuration: &configuration::Configuration,
    params: DeleteLoadBalancerParams,
) -> Result<(), Error<DeleteLoadBalancerError>> {
    delete_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`delete_load_balancer`], but also returns the response headers.
pub async fn delete_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: DeleteLoadBalancerParams,
) -> Result<((), reqwest::header::HeaderMap), Error<DeleteLoadBalancerError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/{id}", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(((), local_var_headers))
    } else {
        let local_var_entity: Option<DeleteLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Delete a service of a Load Balancer.
pub async fn delete_service(
    configuration: &configuration::Configuration,
    params: DeleteServiceParams,
) -> Result<models::DeleteServiceResponse, Error<DeleteServiceError>> {
    delete_service_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`delete_service`], but also returns the response headers.
pub async fn delete_service_with_headers(
    configuration: &configuration::Configuration,
    params: DeleteServiceParams,
) -> Result<(models::DeleteServiceResponse, reqwest::header::HeaderMap), Error<DeleteServiceError>>
{
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let delete_service_request = params.delete_service_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/delete_service",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&delete_service_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<DeleteServiceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Detaches a Load Balancer from a network.
pub async fn detach_load_balancer_from_network(
    configuration: &configuration::Configuration,
    params: DetachLoadBalancerFromNetworkParams,
) -> Result<models::DetachLoadBalancerFromNetworkResponse, Error<DetachLoadBalancerFromNetworkError>>
{
    detach_load_balancer_from_network_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`detach_load_balancer_from_network`], but also returns the response headers.
pub async fn detach_load_balancer_from_network_with_headers(
    configuration: &configuration::Configuration,
    params: DetachLoadBalancerFromNetworkParams,
) -> Result<
    (
        models::DetachLoadBalancerFromNetworkResponse,
        reqwest::header::HeaderMap,
    ),
    Error<DetachLoadBalancerFromNetworkError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let detach_load_balancer_from_network_request =
        params.detach_load_balancer_from_network_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/detach_from_network",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&detach_load_balancer_from_network_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<DetachLoadBalancerFromNetworkError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Disable the public interface of a Load Balancer. The Load Balancer will be not accessible from the internet via its public IPs.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `422` | `load_balancer_not_attached_to_network` | The Load Balancer is not attached to a network | | `422` | `targets_without_use_private_ip` | The Load Balancer has targets that use the public IP instead of the private IP |
pub async fn disable_public_interface_of_load_balancer(
    configuration: &configuration::Configuration,
    params: DisablePublicInterfaceOfLoadBalancerParams,
) -> Result<
    models::DisablePublicInterfaceOfLoadBalancerResponse,
    Error<DisablePublicInterfaceOfLoadBalancerError>,
> {
    disable_public_interface_of_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`disable_public_interface_of_load_balancer`], but also returns the response headers.
pub async fn disable_public_interface_of_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: DisablePublicInterfaceOfLoadBalancerParams,
) -> Result<
    (
        models::DisablePublicInterfaceOfLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<DisablePublicInterfaceOfLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/disable_public_interface",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<DisablePublicInterfaceOfLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Enable the public interface of a Load Balancer. The Load Balancer will be accessible from the internet via its public IPs.
pub async fn enable_public_interface_of_load_balancer(
    configuration: &configuration::Configuration,
    params: EnablePublicInterfaceOfLoadBalancerParams,
) -> Result<
    models::EnablePublicInterfaceOfLoadBalancerResponse,
    Error<EnablePublicInterfaceOfLoadBalancerError>,
> {
    enable_public_interface_of_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`enable_public_interface_of_load_balancer`], but also returns the response headers.
pub async fn enable_public_interface_of_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: EnablePublicInterfaceOfLoadBalancerParams,
) -> Result<
    (
        models::EnablePublicInterfaceOfLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<EnablePublicInterfaceOfLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/enable_public_interface",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<EnablePublicInterfaceOfLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// **Deprecated**: This operation is deprecated, see our [changelog](https://docs.hetzner.cloud/changelog#2026-04-30-deprecate-get-resource-action-endpoints) for more details.  Returns a specific Action for a Load Balancer.
pub async fn get_action_for_load_balancer(
    configuration: &configuration::Configuration,
    params: GetActionForLoadBalancerParams,
) -> Result<models::GetActionResponse, Error<GetActionForLoadBalancerError>> {
    get_action_for_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`get_action_for_load_balancer`], but also returns the response headers.
pub async fn get_action_for_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: GetActionForLoadBalancerParams,
) -> Result<
    (models::GetActionResponse, reqwest::header::HeaderMap),
    Error<GetActionForLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let action_id = params.action_id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/{action_id}",
        local_base_path,
        id = id,
        action_id = action_id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<GetActionForLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Gets a specific Load Balancer object.
pub async fn get_load_balancer(
    configuration: &configuration::Configuration,
    params: GetLoadBalancerParams,
) -> Result<models::GetLoadBalancerResponse, Error<GetLoadBalancerError>> {
    get_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`get_load_balancer`], but also returns the response headers.
pub async fn get_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: GetLoadBalancerParams,
) -> Result<
    (models::GetLoadBalancerResponse, reqwest::header::HeaderMap),
    Error<GetLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/{id}", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<GetLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns a specific Action object.
pub async fn get_load_balancer_action(
    configuration: &configuration::Configuration,
    params: GetLoadBalancerActionParams,
) -> Result<models::GetActionResponse, Error<GetLoadBalancerActionError>> {
    get_load_balancer_action_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`get_load_balancer_action`], but also returns the response headers.
pub async fn get_load_balancer_action_with_headers(
    configuration: &configuration::Configuration,
    params: GetLoadBalancerActionParams,
) -> Result<
    (models::GetActionResponse, reqwest::header::HeaderMap),
    Error<GetLoadBalancerActionError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/actions/{id}", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<GetLoadBalancerActionError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// You must specify the type of metric to get: `open_connections`, `connections_per_second`, `requests_per_second` or `bandwidth`. You can also specify more than one type by comma separation, e.g. `requests_per_second,bandwidth`.  Depending on the type you will get different time series data:  |Type | Timeseries | Unit | Description | |---- |------------|------|-------------| | open_connections | open_connections | number | Open connections | | connections_per_second | connections_per_second | connections/s | Connections per second | | requests_per_second | requests_per_second | requests/s | Requests per second | | bandwidth | bandwidth.in | bytes/s | Ingress bandwidth | || bandwidth.out | bytes/s | Egress bandwidth |  Metrics are available for the last 30 days only.  If you do not provide the step argument we will automatically adjust it so that 200 samples are returned.  We limit the number of samples to a maximum of 500 and will adjust the step parameter accordingly.
pub async fn get_metrics_for_loadbalancer(
    configuration: &configuration::Configuration,
    params: GetMetricsForLoadbalancerParams,
) -> Result<models::GetMetricsForLoadbalancerResponse, Error<GetMetricsForLoadbalancerError>> {
    get_metrics_for_loadbalancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`get_metrics_for_loadbalancer`], but also returns the response headers.
pub async fn get_metrics_for_loadbalancer_with_headers(
    configuration: &configuration::Configuration,
    params: GetMetricsForLoadbalancerParams,
) -> Result<
    (
        models::GetMetricsForLoadbalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<GetMetricsForLoadbalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let r#type = params.r#type;
    let start = params.start;
    let end = params.end;
    let step = params.step;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/{id}/metrics", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = match "multi" {
        "multi" => local_var_req_builder.query(
            &r#type
                .iter()
                .map(|p| ("type".to_owned(), p.to_string()))
                .collect::<Vec<(std::string::String, std::string::String)>>(),
        ),
        _ => local_var_req_builder.query(&[(
            "type",
            &r#type
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<String>>()
                .join(",")
                .to_string(),
        )]),
    };
    local_var_req_builder = local_var_req_builder.query(&[("start", &start.to_string())]);
    local_var_req_builder = local_var_req_builder.query(&[("end", &end.to_string())]);
    if let Some(ref local_var_str) = step {
        local_var_req_builder =
            local_var_req_builder.query(&[("step", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<GetMetricsForLoadbalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns all Action objects for a Load Balancer. You can sort the results by using the `sort` URI parameter, and filter them with the `status` parameter.
pub async fn list_actions_for_load_balancer(
    configuration: &configuration::Configuration,
    params: ListActionsForLoadBalancerParams,
) -> Result<models::ListActionsResponse, Error<ListActionsForLoadBalancerError>> {
    list_actions_for_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`list_actions_for_load_balancer`], but also returns the response headers.
pub async fn list_actions_for_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: ListActionsForLoadBalancerParams,
) -> Result<
    (models::ListActionsResponse, reqwest::header::HeaderMap),
    Error<ListActionsForLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let sort = params.sort;
    let status = params.status;
    let page = params.page;
    let per_page = params.per_page;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/{id}/actions", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = sort {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("sort".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "sort",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = status {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("status".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "status",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = page {
        local_var_req_builder =
            local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = per_page {
        local_var_req_builder =
            local_var_req_builder.query(&[("per_page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ListActionsForLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns all Action objects. You can `sort` the results by using the sort URI parameter, and filter them with the `status` and `id` parameter.
pub async fn list_load_balancer_actions(
    configuration: &configuration::Configuration,
    params: ListLoadBalancerActionsParams,
) -> Result<models::ListActionsResponse, Error<ListLoadBalancerActionsError>> {
    list_load_balancer_actions_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`list_load_balancer_actions`], but also returns the response headers.
pub async fn list_load_balancer_actions_with_headers(
    configuration: &configuration::Configuration,
    params: ListLoadBalancerActionsParams,
) -> Result<
    (models::ListActionsResponse, reqwest::header::HeaderMap),
    Error<ListLoadBalancerActionsError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let sort = params.sort;
    let status = params.status;
    let page = params.page;
    let per_page = params.per_page;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/actions", local_base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = id {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("id".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "id",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = sort {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("sort".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "sort",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = status {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("status".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "status",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = page {
        local_var_req_builder =
            local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = per_page {
        local_var_req_builder =
            local_var_req_builder.query(&[("per_page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ListLoadBalancerActionsError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Gets all existing Load Balancers that you have available.
pub async fn list_load_balancers(
    configuration: &configuration::Configuration,
    params: ListLoadBalancersParams,
) -> Result<models::ListLoadBalancersResponse, Error<ListLoadBalancersError>> {
    list_load_balancers_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`list_load_balancers`], but also returns the response headers.
pub async fn list_load_balancers_with_headers(
    configuration: &configuration::Configuration,
    params: ListLoadBalancersParams,
) -> Result<
    (
        models::ListLoadBalancersResponse,
        reqwest::header::HeaderMap,
    ),
    Error<ListLoadBalancersError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let sort = params.sort;
    let name = params.name;
    let label_selector = params.label_selector;
    let page = params.page;
    let per_page = params.per_page;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers", local_base_path);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = sort {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(
                &local_var_str
                    .iter()
                    .map(|p| ("sort".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => local_var_req_builder.query(&[(
                "sort",
                &local_var_str
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref local_var_str) = name {
        local_var_req_builder =
            local_var_req_builder.query(&[("name", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = label_selector {
        local_var_req_builder =
            local_var_req_builder.query(&[("label_selector", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = page {
        local_var_req_builder =
            local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = per_page {
        local_var_req_builder =
            local_var_req_builder.query(&[("per_page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ListLoadBalancersError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Removes a target from a Load Balancer.
pub async fn remove_target(
    configuration: &configuration::Configuration,
    params: RemoveTargetParams,
) -> Result<models::RemoveTargetResponse, Error<RemoveTargetError>> {
    remove_target_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`remove_target`], but also returns the response headers.
pub async fn remove_target_with_headers(
    configuration: &configuration::Configuration,
    params: RemoveTargetParams,
) -> Result<(models::RemoveTargetResponse, reqwest::header::HeaderMap), Error<RemoveTargetError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let remove_target_request = params.remove_target_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/remove_target",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&remove_target_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<RemoveTargetError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates a Load Balancer. You can update a Load Balancer’s name and a Load Balancer’s labels.  Note: if the Load Balancer object changes during the request, the response will be a “conflict” error.
pub async fn replace_load_balancer(
    configuration: &configuration::Configuration,
    params: ReplaceLoadBalancerParams,
) -> Result<models::ReplaceLoadBalancerResponse, Error<ReplaceLoadBalancerError>> {
    replace_load_balancer_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`replace_load_balancer`], but also returns the response headers.
pub async fn replace_load_balancer_with_headers(
    configuration: &configuration::Configuration,
    params: ReplaceLoadBalancerParams,
) -> Result<
    (
        models::ReplaceLoadBalancerResponse,
        reqwest::header::HeaderMap,
    ),
    Error<ReplaceLoadBalancerError>,
> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let replace_load_balancer_request = params.replace_load_balancer_request;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!("{}/load_balancers/{id}", local_base_path, id = id);
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&replace_load_balancer_request);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<ReplaceLoadBalancerError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Updates a Load Balancer Service.  #### Operation specific errors  | Status | Code | Description | | --- | --- | --- | | `422` | `source_port_already_used` | The source port you are trying to add is already in use |
pub async fn update_service(
    configuration: &configuration::Configuration,
    params: UpdateServiceParams,
) -> Result<models::UpdateServiceResponse, Error<UpdateServiceError>> {
    update_service_with_headers(configuration, params)
        .await
        .map(|(local_var_entity, _)| local_var_entity)
}

/// Same as [`update_service`], but also returns the response headers.
pub async fn update_service_with_headers(
    configuration: &configuration::Configuration,
    params: UpdateServiceParams,
) -> Result<(models::UpdateServiceResponse, reqwest::header::HeaderMap), Error<UpdateServiceError>>
{
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let update_load_balancer_service = params.update_load_balancer_service;

    let local_var_client = &local_var_configuration.client;

    let local_base_path = local_var_configuration.get_base_path("https://api.hetzner.cloud/v1");
    let local_var_uri_str = format!(
        "{}/load_balancers/{id}/actions/update_service",
        local_base_path,
        id = id
    );
    let mut local_var_req_builder =
        local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder =
            local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    local_var_req_builder = local_var_req_builder.json(&update_load_balancer_service);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_headers = local_var_resp.headers().clone();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content)
            .map(|local_var_entity| (local_var_entity, local_var_headers))
            .map_err(Error::from)
    } else {
        let local_var_entity: Option<UpdateServiceError> =
            serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent {
            status: local_var_status,
            headers: Box::new(local_var_headers),
            content: local_var_content,
            entity: local_var_entity,
        };
        Err(Error::ResponseError(local_var_error))
    }
}
