/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 3372012-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddServerToPlacementGroupResponse : Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/add_to_placement_group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddServerToPlacementGroupResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl AddServerToPlacementGroupResponse {
    /// Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/add_to_placement_group
    pub fn new(action: models::Action) -> AddServerToPlacementGroupResponse {
        AddServerToPlacementGroupResponse {
            action: Box::new(action),
        }
    }
}
