/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddTargetResponse : Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/add_target
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddTargetResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl AddTargetResponse {
    /// Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/add_target
    pub fn new(action: models::Action) -> AddTargetResponse {
        AddTargetResponse {
            action: Box::new(action),
        }
    }
}
