/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApplyToResourcesResponse : Response to POST https://api.hetzner.cloud/v1/firewalls/{id}/actions/apply_to_resources



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyToResourcesResponse {
    #[serde(rename = "actions")]
    pub actions: Vec<crate::models::Action>,
}

impl ApplyToResourcesResponse {
    /// Response to POST https://api.hetzner.cloud/v1/firewalls/{id}/actions/apply_to_resources
    pub fn new(actions: Vec<crate::models::Action>) -> ApplyToResourcesResponse {
        ApplyToResourcesResponse {
            actions,
        }
    }
}


