/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 4b3f595
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeZonesProtectionResponse : Response to POST https://api.hetzner.cloud/v1/zones/{id_or_name}/actions/change_protection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeZonesProtectionResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl ChangeZonesProtectionResponse {
    /// Response to POST https://api.hetzner.cloud/v1/zones/{id_or_name}/actions/change_protection
    pub fn new(action: models::Action) -> ChangeZonesProtectionResponse {
        ChangeZonesProtectionResponse {
            action: Box::new(action),
        }
    }
}
