/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChangeAliasIpsOfNetworkResponse : Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/change_alias_ips



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeAliasIpsOfNetworkResponse {
    #[serde(rename = "action")]
    pub action: crate::models::Action,
}

impl ChangeAliasIpsOfNetworkResponse {
    /// Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/change_alias_ips
    pub fn new(action: crate::models::Action) -> ChangeAliasIpsOfNetworkResponse {
        ChangeAliasIpsOfNetworkResponse {
            action,
        }
    }
}


