/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 7cfb4a9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeNetworkProtectionRequest : Request for POST https://api.hetzner.cloud/v1/networks/{id}/actions/change_protection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeNetworkProtectionRequest {
    /// Delete protection setting.  If true, prevents the [Network](#networks) from being deleted.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
}

impl ChangeNetworkProtectionRequest {
    /// Request for POST https://api.hetzner.cloud/v1/networks/{id}/actions/change_protection
    pub fn new() -> ChangeNetworkProtectionRequest {
        ChangeNetworkProtectionRequest { delete: None }
    }
}
