/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 18354c8
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeReverseDnsEntryForThisLoadBalancerResponse : Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/change_dns_ptr
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeReverseDnsEntryForThisLoadBalancerResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl ChangeReverseDnsEntryForThisLoadBalancerResponse {
    /// Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/change_dns_ptr
    pub fn new(action: models::Action) -> ChangeReverseDnsEntryForThisLoadBalancerResponse {
        ChangeReverseDnsEntryForThisLoadBalancerResponse {
            action: Box::new(action),
        }
    }
}
