/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 4b3f595
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeProtectionRequest : Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/actions/change_protection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeProtectionRequest {
    /// Prevent the Resource from being deleted.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
}

impl ChangeProtectionRequest {
    /// Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/actions/change_protection
    pub fn new() -> ChangeProtectionRequest {
        ChangeProtectionRequest { delete: None }
    }
}
