/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.20.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateImageFromServerResponse : Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/create_image
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateImageFromServerResponse {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Box<models::Action>>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<models::Image>>,
}

impl CreateImageFromServerResponse {
    /// Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/create_image
    pub fn new() -> CreateImageFromServerResponse {
        CreateImageFromServerResponse {
            action: None,
            image: None,
        }
    }
}
