/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateFirewallRequest : Request for POST https://api.hetzner.cloud/v1/firewalls



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFirewallRequest {
    /// Name of the Firewall
    #[serde(rename = "name")]
    pub name: String,
    /// User-defined labels (key-value pairs)
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Array of rules
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<crate::models::Rule>>,
    /// Resources the Firewall should be applied to after creation
    #[serde(rename = "apply_to", skip_serializing_if = "Option::is_none")]
    pub apply_to: Option<Vec<crate::models::FirewallResource>>,
}

impl CreateFirewallRequest {
    /// Request for POST https://api.hetzner.cloud/v1/firewalls
    pub fn new(name: String) -> CreateFirewallRequest {
        CreateFirewallRequest {
            name,
            labels: None,
            rules: None,
            apply_to: None,
        }
    }
}


