/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: f6511ca-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSubaccountResponse : Response to POST https://api.hetzner.com/v1/storage_boxes/{id}/subaccounts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubaccountResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
    #[serde(rename = "subaccount")]
    pub subaccount: Box<models::CreateSubaccountResponseSubaccount>,
}

impl CreateSubaccountResponse {
    /// Response to POST https://api.hetzner.com/v1/storage_boxes/{id}/subaccounts
    pub fn new(
        action: models::Action,
        subaccount: models::CreateSubaccountResponseSubaccount,
    ) -> CreateSubaccountResponse {
        CreateSubaccountResponse {
            action: Box::new(action),
            subaccount: Box::new(subaccount),
        }
    }
}
