/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: b12c1e9-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSnapshotResponseSnapshot {
    /// ID of the Storage Box Snapshot.
    #[serde(rename = "id")]
    pub id: i64,
    /// ID of the Storage Box.
    #[serde(rename = "storage_box")]
    pub storage_box: i64,
}

impl CreateSnapshotResponseSnapshot {
    pub fn new(id: i64, storage_box: i64) -> CreateSnapshotResponseSnapshot {
        CreateSnapshotResponseSnapshot { id, storage_box }
    }
}
