/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: in-sync
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSnapshotRequest : Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/snapshots
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSnapshotRequest {
    /// Description of the Storage Box Snapshot.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreateSnapshotRequest {
    /// Request for POST https://api.hetzner.com/v1/storage_boxes/{id}/snapshots
    pub fn new() -> CreateSnapshotRequest {
        CreateSnapshotRequest { description: None }
    }
}
