/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLoadBalancerRequestOneOf1 {
    /// ID or name of Location to create Load Balancer in
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
}

impl CreateLoadBalancerRequestOneOf1 {
    pub fn new() -> CreateLoadBalancerRequestOneOf1 {
        CreateLoadBalancerRequestOneOf1 {
            location: None,
        }
    }
}


