/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSshKeyResponse {
    #[serde(rename = "ssh_key")]
    pub ssh_key: crate::models::SshKey,
}

impl CreateSshKeyResponse {
    pub fn new(ssh_key: crate::models::SshKey) -> CreateSshKeyResponse {
        CreateSshKeyResponse {
            ssh_key,
        }
    }
}


