/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateCertificateResponse : Response to POST https://api.hetzner.cloud/v1/certificates



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCertificateResponse {
    #[serde(rename = "certificate")]
    pub certificate: crate::models::Certificate,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<crate::models::ActionOptional>,
}

impl CreateCertificateResponse {
    /// Response to POST https://api.hetzner.cloud/v1/certificates
    pub fn new(certificate: crate::models::Certificate) -> CreateCertificateResponse {
        CreateCertificateResponse {
            certificate,
            action: None,
        }
    }
}


