/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 3372012-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteSubnetFromNetworkResponse : Response to POST https://api.hetzner.cloud/v1/networks/{id}/actions/delete_subnet
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteSubnetFromNetworkResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl DeleteSubnetFromNetworkResponse {
    /// Response to POST https://api.hetzner.cloud/v1/networks/{id}/actions/delete_subnet
    pub fn new(action: models::Action) -> DeleteSubnetFromNetworkResponse {
        DeleteSubnetFromNetworkResponse {
            action: Box::new(action),
        }
    }
}
