/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteSnapshotResponse : Response to DELETE https://api.hetzner.com/v1/storage_boxes/{id}/snapshots/{snapshot_id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteSnapshotResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl DeleteSnapshotResponse {
    /// Response to DELETE https://api.hetzner.com/v1/storage_boxes/{id}/snapshots/{snapshot_id}
    pub fn new(action: models::Action) -> DeleteSnapshotResponse {
        DeleteSnapshotResponse {
            action: Box::new(action),
        }
    }
}
