/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: b12c1e9-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteStorageBoxResponse : Response to DELETE https://api.hetzner.com/v1/storage_boxes/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteStorageBoxResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl DeleteStorageBoxResponse {
    /// Response to DELETE https://api.hetzner.com/v1/storage_boxes/{id}
    pub fn new(action: models::Action) -> DeleteStorageBoxResponse {
        DeleteStorageBoxResponse {
            action: Box::new(action),
        }
    }
}
