/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.21.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DetachLoadBalancerFromNetworkResponse : Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/detach_from_network
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetachLoadBalancerFromNetworkResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl DetachLoadBalancerFromNetworkResponse {
    /// Response to POST https://api.hetzner.cloud/v1/load_balancers/{id}/actions/detach_from_network
    pub fn new(action: models::Action) -> DetachLoadBalancerFromNetworkResponse {
        DetachLoadBalancerFromNetworkResponse {
            action: Box::new(action),
        }
    }
}
