/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetMetricsForServerResponse : Response to GET https://api.hetzner.cloud/v1/servers/{id}/metrics{?type,start,end,step}



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMetricsForServerResponse {
    #[serde(rename = "metrics")]
    pub metrics: crate::models::GetMetricsForServerResponseMetrics,
}

impl GetMetricsForServerResponse {
    /// Response to GET https://api.hetzner.cloud/v1/servers/{id}/metrics{?type,start,end,step}
    pub fn new(metrics: crate::models::GetMetricsForServerResponseMetrics) -> GetMetricsForServerResponse {
        GetMetricsForServerResponse {
            metrics,
        }
    }
}


