/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: main
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLoadBalancerTypeResponse : Response to GET https://api.hetzner.cloud/v1/load_balancer_types/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoadBalancerTypeResponse {
    #[serde(rename = "load_balancer_type")]
    pub load_balancer_type: Box<models::LoadBalancerType>,
}

impl GetLoadBalancerTypeResponse {
    /// Response to GET https://api.hetzner.cloud/v1/load_balancer_types/{id}
    pub fn new(load_balancer_type: models::LoadBalancerType) -> GetLoadBalancerTypeResponse {
        GetLoadBalancerTypeResponse {
            load_balancer_type: Box::new(load_balancer_type),
        }
    }
}
