/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.28.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetDataCenterResponse : Response to GET https://api.hetzner.cloud/v1/datacenters/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDataCenterResponse {
    #[serde(rename = "datacenter")]
    pub datacenter: Box<models::DataCenter>,
}

impl GetDataCenterResponse {
    /// Response to GET https://api.hetzner.cloud/v1/datacenters/{id}
    pub fn new(datacenter: models::DataCenter) -> GetDataCenterResponse {
        GetDataCenterResponse {
            datacenter: Box::new(datacenter),
        }
    }
}
