/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: d9f5490-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetMultipleActionsResponse : Response to GET https://api.hetzner.cloud/v1/actions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMultipleActionsResponse {
    #[serde(rename = "actions")]
    pub actions: Vec<models::ActionWithOptionalError>,
}

impl GetMultipleActionsResponse {
    /// Response to GET https://api.hetzner.cloud/v1/actions
    pub fn new(actions: Vec<models::ActionWithOptionalError>) -> GetMultipleActionsResponse {
        GetMultipleActionsResponse { actions }
    }
}
