/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 3372012-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLocationResponse : Response to GET https://api.hetzner.cloud/v1/locations/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLocationResponse {
    #[serde(rename = "location")]
    pub location: Box<models::Location>,
}

impl GetLocationResponse {
    /// Response to GET https://api.hetzner.cloud/v1/locations/{id}
    pub fn new(location: models::Location) -> GetLocationResponse {
        GetLocationResponse {
            location: Box::new(location),
        }
    }
}
