/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: b12c1e9-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetZoneResponse : Response to GET https://api.hetzner.cloud/v1/zones/{id_or_name}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetZoneResponse {
    #[serde(rename = "zone")]
    pub zone: Box<models::Zone>,
}

impl GetZoneResponse {
    /// Response to GET https://api.hetzner.cloud/v1/zones/{id_or_name}
    pub fn new(zone: models::Zone) -> GetZoneResponse {
        GetZoneResponse {
            zone: Box::new(zone),
        }
    }
}
