/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.21.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetActionForImageResponse : Response to GET https://api.hetzner.cloud/v1/images/{id}/actions/{action_id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetActionForImageResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl GetActionForImageResponse {
    /// Response to GET https://api.hetzner.cloud/v1/images/{id}/actions/{action_id}
    pub fn new(action: models::Action) -> GetActionForImageResponse {
        GetActionForImageResponse {
            action: Box::new(action),
        }
    }
}
