/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.24.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetLoadBalancerResponse : Response to GET https://api.hetzner.cloud/v1/load_balancers/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLoadBalancerResponse {
    #[serde(rename = "load_balancer")]
    pub load_balancer: Box<models::LoadBalancer>,
}

impl GetLoadBalancerResponse {
    /// Response to GET https://api.hetzner.cloud/v1/load_balancers/{id}
    pub fn new(load_balancer: models::LoadBalancer) -> GetLoadBalancerResponse {
        GetLoadBalancerResponse {
            load_balancer: Box::new(load_balancer),
        }
    }
}
