/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSpecificFloatingIpResponse {
    #[serde(rename = "floating_ip")]
    pub floating_ip: crate::models::FloatingIp,
}

impl GetSpecificFloatingIpResponse {
    pub fn new(floating_ip: crate::models::FloatingIp) -> GetSpecificFloatingIpResponse {
        GetSpecificFloatingIpResponse {
            floating_ip,
        }
    }
}


