/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImageResponse {
    #[serde(rename = "image")]
    pub image: crate::models::Image,
}

impl GetImageResponse {
    pub fn new(image: crate::models::Image) -> GetImageResponse {
        GetImageResponse {
            image,
        }
    }
}


