/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListImagesResponse : Response to GET https://api.hetzner.cloud/v1/images{?sort,type,status,bound_to,name,label_selector}



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListImagesResponse {
    #[serde(rename = "images")]
    pub images: Vec<crate::models::Image>,
}

impl ListImagesResponse {
    /// Response to GET https://api.hetzner.cloud/v1/images{?sort,type,status,bound_to,name,label_selector}
    pub fn new(images: Vec<crate::models::Image>) -> ListImagesResponse {
        ListImagesResponse {
            images,
        }
    }
}


