/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.22.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListActionsForServerResponse : Response to GET https://api.hetzner.cloud/v1/servers/{id}/actions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListActionsForServerResponse {
    #[serde(rename = "actions")]
    pub actions: Vec<models::Action>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListActionsForServerResponse {
    /// Response to GET https://api.hetzner.cloud/v1/servers/{id}/actions
    pub fn new(actions: Vec<models::Action>, meta: models::Meta) -> ListActionsForServerResponse {
        ListActionsForServerResponse {
            actions,
            meta: Box::new(meta),
        }
    }
}
