/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListServersResponse : Response to GET https://api.hetzner.cloud/v1/servers



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServersResponse {
    #[serde(rename = "servers")]
    pub servers: Vec<crate::models::Server>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<crate::models::Meta>>,
}

impl ListServersResponse {
    /// Response to GET https://api.hetzner.cloud/v1/servers
    pub fn new(servers: Vec<crate::models::Server>) -> ListServersResponse {
        ListServersResponse {
            servers,
            meta: None,
        }
    }
}


