/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 7cfb4a9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListSnapshotsForStorageBoxResponse : Response to GET https://api.hetzner.com/v1/storage_boxes/{id}/snapshots
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSnapshotsForStorageBoxResponse {
    #[serde(rename = "snapshots")]
    pub snapshots: Vec<models::Snapshot>,
}

impl ListSnapshotsForStorageBoxResponse {
    /// Response to GET https://api.hetzner.com/v1/storage_boxes/{id}/snapshots
    pub fn new(snapshots: Vec<models::Snapshot>) -> ListSnapshotsForStorageBoxResponse {
        ListSnapshotsForStorageBoxResponse { snapshots }
    }
}
