/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListFloatingIpsResponse : Response to GET https://api.hetzner.cloud/v1/floating_ips{?sort,label_selector,name}



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListFloatingIpsResponse {
    #[serde(rename = "floating_ips")]
    pub floating_ips: Vec<crate::models::FloatingIp>,
}

impl ListFloatingIpsResponse {
    /// Response to GET https://api.hetzner.cloud/v1/floating_ips{?sort,label_selector,name}
    pub fn new(floating_ips: Vec<crate::models::FloatingIp>) -> ListFloatingIpsResponse {
        ListFloatingIpsResponse {
            floating_ips,
        }
    }
}


