/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 4f5630d-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPricesResponsePricingPrimaryIps {
    /// Price of the [Primary IP](#primary-ips) type per [Location](#locations).
    #[serde(rename = "prices")]
    pub prices: Vec<models::PricePerTimeWithoutTraffic>,
    #[serde(rename = "type")]
    pub r#type: models::IpType,
}

impl ListPricesResponsePricingPrimaryIps {
    pub fn new(
        prices: Vec<models::PricePerTimeWithoutTraffic>,
        r#type: models::IpType,
    ) -> ListPricesResponsePricingPrimaryIps {
        ListPricesResponsePricingPrimaryIps { prices, r#type }
    }
}
