/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.20.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListLoadBalancersResponse : Response to GET https://api.hetzner.cloud/v1/load_balancers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLoadBalancersResponse {
    #[serde(rename = "load_balancers")]
    pub load_balancers: Vec<models::LoadBalancer>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::Meta>>,
}

impl ListLoadBalancersResponse {
    /// Response to GET https://api.hetzner.cloud/v1/load_balancers
    pub fn new(load_balancers: Vec<models::LoadBalancer>) -> ListLoadBalancersResponse {
        ListLoadBalancersResponse {
            load_balancers,
            meta: None,
        }
    }
}
