/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListLoadBalancersResponse : Response to GET https://api.hetzner.cloud/v1/load_balancers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListLoadBalancersResponse {
    #[serde(rename = "load_balancers")]
    pub load_balancers: Vec<models::LoadBalancer>,
    #[serde(rename = "meta")]
    pub meta: Box<models::Meta>,
}

impl ListLoadBalancersResponse {
    /// Response to GET https://api.hetzner.cloud/v1/load_balancers
    pub fn new(
        load_balancers: Vec<models::LoadBalancer>,
        meta: models::Meta,
    ) -> ListLoadBalancersResponse {
        ListLoadBalancersResponse {
            load_balancers,
            meta: Box::new(meta),
        }
    }
}
