/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.20.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListServerTypesResponse : Response to GET https://api.hetzner.cloud/v1/server_types
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListServerTypesResponse {
    #[serde(rename = "server_types")]
    pub server_types: Vec<models::ServerType>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::Meta>>,
}

impl ListServerTypesResponse {
    /// Response to GET https://api.hetzner.cloud/v1/server_types
    pub fn new(server_types: Vec<models::ServerType>) -> ListServerTypesResponse {
        ListServerTypesResponse {
            server_types,
            meta: None,
        }
    }
}
