/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListSshKeysResponse : Response to GET https://api.hetzner.cloud/v1/ssh_keys{?sort,name,fingerprint,label_selector}



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSshKeysResponse {
    #[serde(rename = "ssh_keys")]
    pub ssh_keys: Vec<crate::models::SshKey>,
}

impl ListSshKeysResponse {
    /// Response to GET https://api.hetzner.cloud/v1/ssh_keys{?sort,name,fingerprint,label_selector}
    pub fn new(ssh_keys: Vec<crate::models::SshKey>) -> ListSshKeysResponse {
        ListSshKeysResponse {
            ssh_keys,
        }
    }
}


