/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.20.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListActionsForCertificateResponse : Response to GET https://api.hetzner.cloud/v1/certificates/{id}/actions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListActionsForCertificateResponse {
    #[serde(rename = "actions")]
    pub actions: Vec<models::Action>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::Meta>>,
}

impl ListActionsForCertificateResponse {
    /// Response to GET https://api.hetzner.cloud/v1/certificates/{id}/actions
    pub fn new(actions: Vec<models::Action>) -> ListActionsForCertificateResponse {
        ListActionsForCertificateResponse {
            actions,
            meta: None,
        }
    }
}
