/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoadBalancerPublicNet : Public network information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadBalancerPublicNet {
    /// Public Interface enabled or not
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "ipv4")]
    pub ipv4: crate::models::LoadBalancerPublicNetIpv4,
    #[serde(rename = "ipv6")]
    pub ipv6: crate::models::LoadBalancerPublicNetIpv6,
}

impl LoadBalancerPublicNet {
    /// Public network information
    pub fn new(enabled: bool, ipv4: crate::models::LoadBalancerPublicNetIpv4, ipv6: crate::models::LoadBalancerPublicNetIpv6) -> LoadBalancerPublicNet {
        LoadBalancerPublicNet {
            enabled,
            ipv4,
            ipv6,
        }
    }
}


