/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: main
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadBalancerTargetTypeIp {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// List of health statuses of the services on this target. Only present for target types \"server\" and \"ip\".
    #[serde(rename = "health_status")]
    pub health_status: Vec<models::LoadBalancerTargetHealthStatus>,
    #[serde(rename = "ip")]
    pub ip: Box<models::LoadBalancerTargetIp>,
}

impl LoadBalancerTargetTypeIp {
    pub fn new(
        r#type: Type,
        health_status: Vec<models::LoadBalancerTargetHealthStatus>,
        ip: models::LoadBalancerTargetIp,
    ) -> LoadBalancerTargetTypeIp {
        LoadBalancerTargetTypeIp {
            r#type,
            health_status,
            ip: Box::new(ip),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ip")]
    Ip,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ip
    }
}
