/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 76113aa-dirty
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsTimeSeries {
    /// Metrics Timestamps with values.
    #[serde(rename = "values")]
    pub values: Vec<Vec<models::MetricsTimeSeriesValue>>,
}

impl MetricsTimeSeries {
    pub fn new(values: Vec<Vec<models::MetricsTimeSeriesValue>>) -> MetricsTimeSeries {
        MetricsTimeSeries { values }
    }
}
