/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: in-sync
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Network {
    /// Point in time when the Resource was created (in ISO-8601 format).
    #[serde(rename = "created")]
    pub created: String,
    /// Indicates if the routes from this [Network](#networks) should be exposed to the vSwitch connection.
    #[serde(rename = "expose_routes_to_vswitch")]
    pub expose_routes_to_vswitch: bool,
    /// ID of the [Network](#networks).
    #[serde(rename = "id")]
    pub id: i64,
    /// IP range of the [Network](#networks).  Uses CIDR notation.
    #[serde(rename = "ip_range")]
    pub ip_range: String,
    /// User-defined labels (`key/value` pairs) for the Resource. For more information, see \"[Labels](#labels)\".  | User-defined labels (`key/value` pairs) for the Resource.  Note that the set of [Labels](#labels) provided in the request will overwrite the existing one.  For more information, see \"[Labels](#labels)\".  | The Storage Boxes' labels. | The Subaccounts' labels. | The Snapshots' labels.
    #[serde(rename = "labels")]
    pub labels: std::collections::HashMap<String, String>,
    /// Array of IDs of [Load Balancers](#load-balancers) attached to this [Network](#networks).
    #[serde(rename = "load_balancers", skip_serializing_if = "Option::is_none")]
    pub load_balancers: Option<Vec<i64>>,
    /// Name of the [Network](#networks).
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "protection")]
    pub protection: Box<models::Protection>,
    /// Array of routes set in this [Network](#networks).
    #[serde(rename = "routes")]
    pub routes: Vec<models::Route>,
    /// Array of IDs of [Servers](#servers) attached to this [Network](#networks).
    #[serde(rename = "servers")]
    pub servers: Vec<i64>,
    /// List of subnets allocated in this [Network](#networks).
    #[serde(rename = "subnets")]
    pub subnets: Vec<models::SubnetWithGateway>,
}

impl Network {
    pub fn new(
        created: String,
        expose_routes_to_vswitch: bool,
        id: i64,
        ip_range: String,
        labels: std::collections::HashMap<String, String>,
        name: String,
        protection: models::Protection,
        routes: Vec<models::Route>,
        servers: Vec<i64>,
        subnets: Vec<models::SubnetWithGateway>,
    ) -> Network {
        Network {
            created,
            expose_routes_to_vswitch,
            id,
            ip_range,
            labels,
            load_balancers: None,
            name,
            protection: Box::new(protection),
            routes,
            servers,
            subnets,
        }
    }
}
