/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.24.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PricePerTimeMonthly {
    /// Name of the [Location](#locations) the price is for.
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "price_monthly")]
    pub price_monthly: Box<models::Price>,
}

impl PricePerTimeMonthly {
    pub fn new(location: String, price_monthly: models::Price) -> PricePerTimeMonthly {
        PricePerTimeMonthly {
            location,
            price_monthly: Box::new(price_monthly),
        }
    }
}
