/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: in-sync
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveFromPlacementGroupResponse : Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/remove_from_placement_group
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveFromPlacementGroupResponse {
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
}

impl RemoveFromPlacementGroupResponse {
    /// Response to POST https://api.hetzner.cloud/v1/servers/{id}/actions/remove_from_placement_group
    pub fn new(action: models::Action) -> RemoveFromPlacementGroupResponse {
        RemoveFromPlacementGroupResponse {
            action: Box::new(action),
        }
    }
}
