/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: in-sync
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplaceStorageBoxResponse : Response to PUT https://api.hetzner.com/v1/storage_boxes/{id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceStorageBoxResponse {
    #[serde(rename = "storage_box")]
    pub storage_box: Box<models::StorageBox>,
}

impl ReplaceStorageBoxResponse {
    /// Response to PUT https://api.hetzner.com/v1/storage_boxes/{id}
    pub fn new(storage_box: models::StorageBox) -> ReplaceStorageBoxResponse {
        ReplaceStorageBoxResponse {
            storage_box: Box::new(storage_box),
        }
    }
}
