/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReplaceFloatingIpResponse : Response to PUT https://api.hetzner.cloud/v1/floating_ips/{id}



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceFloatingIpResponse {
    #[serde(rename = "floating_ip")]
    pub floating_ip: crate::models::FloatingIp,
}

impl ReplaceFloatingIpResponse {
    /// Response to PUT https://api.hetzner.cloud/v1/floating_ips/{id}
    pub fn new(floating_ip: crate::models::FloatingIp) -> ReplaceFloatingIpResponse {
        ReplaceFloatingIpResponse {
            floating_ip,
        }
    }
}


