/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: in-sync
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplaceSnapshotResponse : Response to PUT https://api.hetzner.com/v1/storage_boxes/{id}/snapshots/{snapshot_id}
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceSnapshotResponse {
    #[serde(rename = "snapshot", skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<Box<models::Snapshot>>,
}

impl ReplaceSnapshotResponse {
    /// Response to PUT https://api.hetzner.com/v1/storage_boxes/{id}/snapshots/{snapshot_id}
    pub fn new() -> ReplaceSnapshotResponse {
        ReplaceSnapshotResponse { snapshot: None }
    }
}
