/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceVolumeResponse {
    #[serde(rename = "volume")]
    pub volume: crate::models::ReplaceVolumeResponseVolume,
}

impl ReplaceVolumeResponse {
    pub fn new(volume: crate::models::ReplaceVolumeResponseVolume) -> ReplaceVolumeResponse {
        ReplaceVolumeResponse {
            volume,
        }
    }
}


