/*
 * Hetzner Cloud API
 *
 * Copied from the official API documentation for the Public Hetzner Cloud.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReplaceFloatingIpRequestLabels : User-defined labels (key-value pairs)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceFloatingIpRequestLabels {
    #[serde(rename = "labelkey", skip_serializing_if = "Option::is_none")]
    pub labelkey: Option<String>,
}

impl ReplaceFloatingIpRequestLabels {
    /// User-defined labels (key-value pairs)
    pub fn new() -> ReplaceFloatingIpRequestLabels {
        ReplaceFloatingIpRequestLabels {
            labelkey: None,
        }
    }
}


