name: Create GitHub release and publish crate to crates.io

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get release version from tag
        id: get_version
        run: echo ::set-output name=tag_version::${GITHUB_REF#refs/tags/v}

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: hcloud-rust v${{ steps.get_version.outputs.tag_version }}
          draft: true
          prerelease: ${{ startsWith(steps.get_version.outputs.tag_version, '0.') }}

      - name: Publish crate to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
